my $str = "MNPBP NAWGB XJIWU IWZZF GJIWR ILYYO EJPOE YTTVO CJFAE RJYXX 
XAJKW ZXSWV WJTAO MLOIE WRFBD CHDXM XNPXG RDYUE IXPBF NATPE 
GNYNV RYNWX QTTZF NJIYO SHIHW XMNGH RANGY CSZPE REYYO EJIWR 
QAZVS GLOIE VOWGX NDJWB XLYME RJIVM VATBD YYJYY KSPDD LTPAR 
NTZZF GATMG ZCGTO WMPXI RATMG ZCGCO JYZPE LNQHM SGYZF GAWXG 
EENMG IBPBM WESXV XIBXS ATQHE GOYNR IPGQX ATSIS QYNWK IWQZE 
XFQAX CYLWG QYQYS BERGG RDOAJ ZKQAE GYNXS TCQBS XXJVI KGQYW 
WDBYO GJIWS WMQYC DYNID CHMGI IJYAO SDGLF GNPDD PLPQF MWQLO 
EHGXM GYTZD MNJYF EJAVG WXIWM ZCDXM XASQM VTGWX QTTHE XJIXH 
XGRGG JEVWF GJPNG IKPXI GJPWV ZXJEG ICSQE LAEKF GYVGY CSQMV 
ZMPXS MNPEF AGPHH XYSHW XPSOD JYGLS ZXYAO CYYDV IXSLZ IXPBH 
QENWM ZXJHW XMNVM OXQTF PPSVK IWMGK ZJQOV ZBNVR ZXRPO GYDPE 
XFWGI XDRWG XWOQQ XSRVS QKNWR WDPYO BDYDS ATWXV GMQYM BACWH 
ZDOAW XWPWF ALEZD MNZZO DEPEO NDNXS TDQVX GNYTD CHQQG ZBZXR 
AETBS QYWXG BTZPW WDCGO RNQAX VAEEE GEMWL SDOAE GDRVS QOYNR 
ZDPKF GYTPG SHCWX MNPJD ALZGW WDNVQ QJCVQ KLPQF CSSNX KYJPD 
VJIWL ZWZWI RYNBM VTGWH WSPAE RNOBY KLOAE GDRXM MNPBS SBVGK 
PYCWI RTSXI ZHPGK ZBVGG RAWOE FYQNS NJIWG XCQBM IRPHW WXCPE 
AAGQD LAWGY MNOBV ZMAGK WJZPE ZXZVA SYQYC BNOAE RATPE AYQKW 
XSVGG ZXYHW XWMNQ WJRXM ZWFBM WASUD PTZXG NKNGS QYTVM ZDPTE 
CBFAR MTYAK IWDWK XYJEF LFMXI WKFOF MENKF GYJVI KWFEL NKOAP 
OLQBS WMEGY ZWPHO IRFKW MNPXG MTTHE QYNYR ZDPYF MUCYY CJPQS 
QYTGY CSTWG YYJPD VATOF SHIHE ANPBR AAZKW XSIVM IVPYW ZXCGK 
BNOHE GNOYS XSWWV PORVS QJIWU WXAKV ZCEGY ZWPHW XANHD GJPGK 
MNPBV WHIHV NBFAI NSPXV";

my @hash1 = qw(
 I 
 A 
 E 
 J 
 X 
 T 
 B 
 M 
 P 
 H 
 L 
 D 
 Z 
 W 
 Q 
 K 
 U 
 Y 
 N 
 G 
 S 
 R 
 V 
 F 
 O 
 C 
);

my @hash0 = qw(
 - 
 I 
 - 
 - 
 - 
 - 
 T 
 - 
 N
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 O 
 - 
 - 
 - 
 - 
 - 
 - 
 E 
 Y 
 J 
);



my $shift0=10;
my $shift1=10;
my $shift2=0;
my $shift3=6;
my $shift4=-5;

my $i = 0;
$str =~ s/ //g;
$str =~ s/\n//g;

for my $chr (split //, $str) {
  decrypt($chr, $i);
  $i += 1;
}

sub decrypt{    
    my $chr = shift;
    my $count = shift;

    my $chr_val = ord($chr)-ord('A');	
    my $new_chr = ord(substr($hash0[$chr_val],0,1));

    $new_chr = $new_chr+$shift0 if ($count % 5 == 0);
    $new_chr = $new_chr+$shift1 if ($count % 5 == 1);
    $new_chr = $new_chr+$shift2 if ($count % 5 == 2);
    $new_chr = $new_chr+$shift3 if ($count % 5 == 3);
    $new_chr = $new_chr+$shift4 if ($count % 5 == 4);

    $new_chr += 26 if ($new_chr < 65);
    $new_chr -= 26 if ($new_chr > 90);
	
    print chr($new_chr);
    print " " if ($count % 5 == 4);
}
